### ISSUE TITLE
**please make sure you do all changes in css file.**

### ISSUE THREAD

**Issue by helindevani** [helindevani/CSS#1]
**please make sure you do all changes in css file.**

**Google Font Link : [poppins](https://fonts.google.com/specimen/Poppins)**

_Originally posted by @hirentimbadiya in https://github.com/hirentimbadiya/Markdown-Previewer/issues/5_

**Comment by Cstrp** [comment]
I added @import for poppins font in css file.

**Comment by helindevani** [comment]
ok i am solve this
